# @package _global_
scenario:
  type_: TaskIncrementalRegression
  hdf5_filename: "eurowind.hdf5"
  num_tasks: 8
  orthogonalize_targets: true

training:
  train_mb_size: 1024
  epochs: 50
  num_workers: 5
