# @package _global_
defaults:
- /scenario/eurowind/base

strategy:
  type_: EWC

  ewc_lambda: 793.9798744773759
model:
  type_: MLP

  layers_hidden:
  - 506
  n_hidden_layers: 1
training:
  lr: 0.003785045447426495
