# @package _global_
defaults:
- /scenario/eurowind/base

model:
  type_: EfficientKAN

  layers_hidden:
  - 124
  - 114
  - 73
  n_hidden_layers: 3
  spline_order: 1
  grid_size: 12
  grid_range: [-4, 4]
  norm: layer
  activation_penalty_weight: 0.1
  entropy_penalty_weight: 1.0
  first_layer_is_linear: true
scenario:
  num_tasks: 1
  orthogonalize_targets: false
training:
  lr: 0.005919803698892875
