# @package _global_
defaults:
- /scenario/riverradar/base

model:
  type_: EfficientKAN
  layers_hidden:
  - 47
  n_hidden_layers: 1
  spline_order: 3
  grid_size: 18
  grid_range: [-2, 2]
  norm: layer
  activation_penalty_weight: 5.0
  entropy_penalty_weight: 0.1
  first_layer_is_linear: false
training:
  lr: 5.51636977369236e-05
