# @package _global_
defaults:
- /scenario/riverradar/base

model:
  type_: PackNet

  layers_hidden:
  - 498
  - 398
  - 244
  n_hidden_layers: 3
  prune_ratio: 0.7937434730097916
  prune_after_p_percent: 0.4344097081785344
training:
  lr: 0.0005329456761416731
