# @package _global_
defaults:
- /scenario/feynman/base

model:
  type_: PackNet

  layers_hidden:
  - 229
  - 441
  - 511
  n_hidden_layers: 3
  prune_ratio: 0.8683547306993352
  prune_after_p_percent: 0.6941259164706891
training:
  lr: 0.026550933455582886
